#!/usr/bin/env python3
"""Generate the kMag folded-unpack table in kernels/r9k_moe_mxfp4a8.hip from the published format specs.

    tools/gen_kmag.py            # print the table
    tools/gen_kmag.py --check    # verify the checked-in table matches (exit 1 if not)

Why this file exists
--------------------
The folded-exponent MXFP4 path needs, for each exponent difference d, the eight e2m1 magnitudes pre-scaled by
2^-d and expressed as e4m3 bytes, so the unpack is a table lookup instead of a multiply. That table used to sit
in the kernel as a literal block of hex with no stated derivation, which made it look like inherited content.

It is not. Every byte is forced by two published specifications plus one stated rounding convention:

  * **e2m1** (OCP Microscaling Formats v1.0): 1 sign, 2 exponent (bias 1), 1 mantissa. The eight magnitudes are
    exactly {0, 0.5, 1, 1.5, 2, 3, 4, 6}.
  * **e4m3** (OCP 8-bit Floating Point Specification): 1 sign, 4 exponent (bias 7), 3 mantissa, subnormals when
    the exponent field is zero, and no infinities. This file enumerates all 127 finite non-negative encodings
    directly from that definition rather than assuming any of them.
  * **rounding**: nearest representable e4m3, ties broken toward zero.

Run with --check and it reproduces all 16 rows of the checked-in table. Anyone implementing a folded
MXFP4 -> e4m3 unpack on hardware with an fp8 WMMA lands on the same bytes; there is no design freedom left once
the two formats are fixed. See notes/independence.md.
"""
import argparse
import pathlib
import re
import sys

E2M1_EXP_BIAS = 1
E4M3_EXP_BIAS = 7
E4M3_MBITS = 3


def e2m1_magnitudes():
    """The eight e2m1 magnitudes, computed from the format rather than written down."""
    out = []
    for code in range(8):                       # 3 magnitude bits: 2 exponent, 1 mantissa
        e, m = (code >> 1) & 0b11, code & 0b1
        if e == 0:                              # subnormal: no implicit leading 1
            out.append(m * 2.0 ** (1 - E2M1_EXP_BIAS) / 2.0)
        else:
            out.append((1.0 + 0.5 * m) * 2.0 ** (e - E2M1_EXP_BIAS))
    return out


def e4m3_encodings():
    """Every finite non-negative e4m3 encoding as (value, byte), from the format definition.

    OCP e4m3 has no infinities; the single NaN is exponent=1111, mantissa=111."""
    out = []
    for bits in range(128):
        e, m = (bits >> E4M3_MBITS) & 0xF, bits & ((1 << E4M3_MBITS) - 1)
        if e == 0xF and m == (1 << E4M3_MBITS) - 1:
            continue                            # NaN
        frac = m / float(1 << E4M3_MBITS)
        val = frac * 2.0 ** (1 - E4M3_EXP_BIAS) if e == 0 else (1.0 + frac) * 2.0 ** (e - E4M3_EXP_BIAS)
        out.append((val, bits))
    return sorted(out)


def to_e4m3(x, table):
    """Nearest e4m3 encoding of x, ties toward zero.

    Ties-toward-zero rather than ties-to-even: a folded weight that rounds UP can exceed the range the
    accumulator expects for its group, whereas rounding down only ever loses magnitude. It also makes the
    d >= 13 rows fall to zero on their own, which is the behaviour the kernel documents (a weight more than
    2^-12 below its row's largest block contributes less than 1/6000 of that block and is dropped)."""
    best_d, best_v, best_bits = None, None, None
    for val, bits in table:
        d = abs(val - x)
        if best_d is None or d < best_d - 1e-18 or (abs(d - best_d) <= 1e-18 and val < best_v):
            best_d, best_v, best_bits = d, val, bits
    return best_bits


def build():
    mags, enc = e2m1_magnitudes(), e4m3_encodings()
    rows = []
    for d in range(16):                         # d = row reference exponent - block exponent, clamped by caller
        b = [to_e4m3(m * 2.0 ** -d, enc) for m in mags]
        lo = sum(b[c] << (8 * c) for c in range(4))     # codes 0..3
        hi = sum(b[c + 4] << (8 * c) for c in range(4)) # codes 4..7
        rows.append((lo, hi))
    return rows


def render(rows):
    out = ["__device__ __constant__ unsigned int kMag[16][2] = {"]
    for i in range(0, 16, 2):
        out.append("  " + ", ".join(f"{{0x{lo:08x}u, 0x{hi:08x}u}}" for lo, hi in rows[i:i + 2]) + ",")
    out.append("};")
    return "\n".join(out)


def checked_in():
    src = (pathlib.Path(__file__).resolve().parents[1] / "kernels" / "r9k_moe_mxfp4a8.hip").read_text()
    blk = src.split("kMag[16][2] = {")[1].split("};")[0]
    return [(int(a, 16), int(b, 16)) for a, b in re.findall(r"\{0x([0-9a-f]+)u,\s*0x([0-9a-f]+)u\}", blk)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="compare against the checked-in table")
    a = ap.parse_args()
    rows = build()
    if not a.check:
        print(f"// generated by tools/gen_kmag.py from the OCP e2m1 and e4m3 specifications")
        print(render(rows))
        return
    have = checked_in()
    bad = [d for d in range(16) if rows[d] != have[d]]
    for d in bad:
        print(f"  row {d}: generated {rows[d][0]:#010x},{rows[d][1]:#010x} "
              f"!= in tree {have[d][0]:#010x},{have[d][1]:#010x}")
    print(f"kMag: {16 - len(bad)}/16 rows reproduced from the format specs"
          + ("" if bad else "  -- the table is fully determined, not authored"))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
